### ISSUE TITLE
指定禅道任务关闭的生效么？

### ISSUE THREAD

**Issue by it-noob** [ihao/git-commit-helper#1]
反复测试禅道任务和 bug 关闭的功能发现未生效，是跟我禅道版本有关么？

**Comment by ihao** [comment]
@it-noob 
你好，不知道你所使用的禅道是什么版本的，我们公司内部是使用的saas版本7.5.1。功能一切正常。

**Comment by ihao** [comment]
另外，请确认一下commit-msg的第51－53行都配置正确了，分别是禅道的地址，用户名，密码这三项
ZT_HOST=""
ZT_USER=""
ZT_PASS=""

**Comment by ihao** [comment]
抱歉，查看了下公司环境，目前这个脚本支持的是专业版7.5.1，对后续新版本的兼容还真没考虑。

**Comment by it-noob** [comment]
谢谢您的回复，我已经根据您回复搞定了，再次感谢。开源版本也是相同思路，更换不同的url即可，以及版本之前差异的参数。再次感谢，测试通过后，我可以在issue上追加针对我这种情况的修复情况。目前使用11.1的稳定版本
